### ISSUE TITLE
How to enable selection functinality in CustomPowerMenu ?

### ISSUE THREAD

**Issue by rushilYiion** [skydoves/PowerMenu#62]
How to enable  setSelectedTextColor() and setSelectedMenuColor() for CustomPowerMenu ??

**Comment by skydoves** [comment]
Hi, @rushilYiion 

Unfortunately, that's impossible.
Because those functions are implemented in the default adapter.
In your custom adapter, you can implement it easily.
You can reference the [default adapter](https://github.com/skydoves/PowerMenu/blob/master/powermenu/src/main/java/com/skydoves/powermenu/MenuListAdapter.java).

Thanks!

**Comment by rushilYiion** [comment]
@skydoves Thanks
